const portals={meebhoomi:"https://meebhoomi.ap.gov.in/",ec:"https://registration.ec.ap.gov.in/ecSearch",lrs:"https://lrsdtcp.ap.gov.in/PublicApplicationSearch",layouts:"https://lrsdtcp.ap.gov.in/dashBoard"};
let properties=JSON.parse(localStorage.getItem("p360_properties")||"[]");
let customers=JSON.parse(localStorage.getItem("p360_customers")||"[]");
const main=document.querySelector("#main");
function save(){localStorage.setItem("p360_properties",JSON.stringify(properties));localStorage.setItem("p360_customers",JSON.stringify(customers))}
function portal(name){window.open(portals[name],"_blank","noopener,noreferrer")}
function shell(title,body){main.innerHTML=`<button class="back" onclick="render('home')">← Dashboard</button><h1>${title}</h1>${body}`}
function render(screen){
 if(screen==="home") main.innerHTML=`<h1>Property Dashboard</h1><input class="search" placeholder="🔎 Search property, survey no., customer..." oninput="quickSearch(this.value)">
 <div class="grid">
 <button class="card" onclick="render('new')"><div class="icon">➕</div><div class="title">New Property</div><div class="desc">Create a property file</div></button>
 <button class="card" onclick="render('land')"><div class="icon">📜</div><div class="title">1-B / Adangal</div><div class="desc">MeeBhoomi</div></button>
 <button class="card" onclick="render('ec')"><div class="icon">📑</div><div class="title">EC Search</div><div class="desc">Document / Survey</div></button>
 <button class="card" onclick="render('lrs')"><div class="icon">📋</div><div class="title">LRS Search</div><div class="desc">Applicant details</div></button>
 <button class="card wide" onclick="render('layouts')"><div class="icon">🏘️</div><div class="title">Completed Layouts</div><div class="desc">LRS / DTCP dashboard</div></button></div>
 <div class="section">Recent Properties</div><div id="recent">${properties.length?properties.slice(-3).reverse().map(p=>propCard(p)).join(""):'<div class="panel">No properties yet. Create your first property file.</div>'}</div>`;
 else if(screen==="properties") {shell("My Properties",properties.length?properties.map(propCard).join(""):'<div class="panel">No properties saved yet.</div>')}
 else if(screen==="new") {shell("New Property",`<div class="panel"><div class="field"><label>Property Name</label><input id="pname" placeholder="e.g. Guntur Site 01"></div><div class="field"><label>District</label><input id="district" placeholder="Guntur"></div><div class="field"><label>Mandal</label><input id="mandal" placeholder="Mandal"></div><div class="field"><label>Village</label><input id="village" placeholder="Village"></div><div class="field"><label>Survey Number</label><input id="survey" placeholder="123/2"></div><div class="field"><label>Extent</label><input id="extent" placeholder="2.50 Acres"></div><div class="field"><label>Customer</label><input id="customer" placeholder="Customer name"></div><button class="btn" onclick="createProperty()">Create Property Profile</button></div>`)}
 else if(screen==="profile"){const p=properties[0]||{name:"Sample Property — Guntur",survey:"123/2",extent:"2.50 Acres"}; profile(p)}
 else if(screen==="customers") {shell("Customers",customers.length?customers.map(c=>`<div class="panel"><b>${c.name}</b><div class="row"><span>Phone</span><b>${c.phone||"—"}</b></div></div>`).join(""):'<div class="panel">Customer CRM is ready for the next database phase.</div>')}
 else if(screen==="land") service("1-B & Adangal","MeeBhoomi","meebhoomi",["District","Mandal","Village","Survey Number"]);
 else if(screen==="ec") service("EC Search","Registration EC Search","ec",["Document / Survey Number","Year / SRO"]);
 else if(screen==="lrs") service("LRS Application Search","LRS / DTCP","lrs",["Applicant Name","Application Number","District / Location"]);
 else if(screen==="layouts") service("Completed Layouts","LRS / DTCP Dashboard","layouts",["District","Mandal","Layout / Applicant"]);
 document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b.dataset.screen===screen));
}
function propCard(p){return `<div class="panel" style="margin-bottom:10px;cursor:pointer" onclick='profile(${JSON.stringify(p)})'><b>${p.name}</b><div class="row"><span>Survey No.</span><b>${p.survey||"—"}</b></div><div class="row"><span>Extent</span><b>${p.extent||"—"}</b></div><div class="row"><span>Verification</span><span class="badge">In Progress</span></div></div>`}
function profile(p){shell("Property Profile",`<div class="panel"><b style="font-size:18px">${p.name}</b><div class="row"><span>District</span><b>${p.district||"—"}</b></div><div class="row"><span>Village</span><b>${p.village||"—"}</b></div><div class="row"><span>Survey No.</span><b>${p.survey||"—"}</b></div><div class="row"><span>Extent</span><b>${p.extent||"—"}</b></div></div><div class="section">Government Verification</div><div class="grid"><button class="card" onclick="render('land')">📜<div class="title">1-B / Adangal</div></button><button class="card" onclick="render('ec')">📑<div class="title">EC</div></button><button class="card" onclick="render('lrs')">📋<div class="title">LRS</div></button><button class="card" onclick="render('layouts')">🏘️<div class="title">Layout</div></button></div><div class="section">Verification Checklist</div><div class="panel">${["Owner / Applicant name","Survey number","Extent","EC entries","LRS status","Layout status"].map(x=>`<div class="row"><span>${x}</span><span class="badge">Review</span></div>`).join("")}</div><button class="btn" onclick="alert('PDF Property Report will be enabled in the report module.')">Share Property Report</button>`)}
function service(title,source,key,fields){shell(title,`<div class="panel">${fields.map((f,i)=>`<div class="field"><label>${f}</label><input id="f${i}" placeholder="Enter ${f.toLowerCase()}"></div>`).join("")}<button class="btn" onclick="portal('${key}')">Open Official ${source}</button><div class="note">This version opens the official government workflow. It does not bypass CAPTCHA, OTP, login, or other portal security controls.</div></div>`)}
function createProperty(){const p={id:"P360-"+Date.now().toString().slice(-6),name:document.querySelector("#pname").value||"Untitled Property",district:document.querySelector("#district").value,mandal:document.querySelector("#mandal").value,village:document.querySelector("#village").value,survey:document.querySelector("#survey").value,extent:document.querySelector("#extent").value,customer:document.querySelector("#customer").value};properties.push(p);if(p.customer)customers.push({name:p.customer});save();profile(p)}
function quickSearch(q){const r=document.querySelector("#recent");const a=properties.filter(p=>JSON.stringify(p).toLowerCase().includes(q.toLowerCase()));r.innerHTML=a.length?a.map(propCard).join(""):'<div class="panel">No matching property.</div>'}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>render(b.dataset.screen));
document.querySelector("#lang").onclick=()=>alert("Telugu interface will be added in the bilingual UI pass.");
render("home");